// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBya_Cc8wmumPtSN9Z72L94JiTqeMMySoE',
    appId: '1:414176667873:web:925a84991de05033732fa0',
    messagingSenderId: '414176667873',
    projectId: 't-app-7062f',
    authDomain: 't-app-7062f.firebaseapp.com',
    storageBucket: 't-app-7062f.firebasestorage.app',
    measurementId: 'G-X8EKD0048Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7KhaDz-INJu9iC-FiAC7gXcq-kXkYrg',
    appId: '1:414176667873:android:56535896985a9d4b732fa0',
    messagingSenderId: '414176667873',
    projectId: 't-app-7062f',
    storageBucket: 't-app-7062f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB66wUOyrGjabK1mj1SasvdYh5fc8SyA8',
    appId: '1:414176667873:ios:fe6be45e95054b15732fa0',
    messagingSenderId: '414176667873',
    projectId: 't-app-7062f',
    storageBucket: 't-app-7062f.firebasestorage.app',
    iosBundleId: 'com.example.tApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB66wUOyrGjabK1mj1SasvdYh5fc8SyA8',
    appId: '1:414176667873:ios:fe6be45e95054b15732fa0',
    messagingSenderId: '414176667873',
    projectId: 't-app-7062f',
    storageBucket: 't-app-7062f.firebasestorage.app',
    iosBundleId: 'com.example.tApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBya_Cc8wmumPtSN9Z72L94JiTqeMMySoE',
    appId: '1:414176667873:web:857c0d31a073585d732fa0',
    messagingSenderId: '414176667873',
    projectId: 't-app-7062f',
    authDomain: 't-app-7062f.firebaseapp.com',
    storageBucket: 't-app-7062f.firebasestorage.app',
    measurementId: 'G-MJG1WWFRB0',
  );

}